/** commons */
export const RECEIVE_DISABLE_FLAG = 'RECEIVE_DISABLE_FLAG';
export const RECEIVE_NAVBAR_OPEN_FLAG = 'RECEIVE_NAVBAR_OPEN_FLAG';
export const RECEIVE_SEARCH_VALUE = 'RECEIVE_SEARCH_VALUE';
export const RECEIVE_DISABLE_CART_BUTTON = 'RECEIVE_DISABLE_CART_BUTTON';
export const RECEIVE_DISABLE_ORDER_BUTTON = 'RECEIVE_DISABLE_ORDER_BUTTON';
export const LOAD_UNPAID_ORDER_LIST = 'LOAD_UNPAID_ORDER_LIST';

/** product type */
export const RECEIVE_PRODUCT_TYPE_LIST = 'RECEIVE_PRODUCT_TYPE_LIST';
export const RECEIVE_PRODUCT_TYPE = 'RECEIVE_PRODUCT_TYPE';

/** menu type */
export const RECEIVE_MENU_TYPE_LIST = 'RECEIVE_MENU_TYPE_LIST';
export const RECEIVE_MENU_TYPE = 'RECEIVE_MENU_TYPE';

/** user type */
export const RECEIVE_USER_TYPE_LIST = 'RECEIVE_USER_TYPE_LIST';
export const RECEIVE_USER_TYPE = 'RECEIVE_USER_TYPE';

/** product */
export const RECEIVE_PRODUCT_SEARCH_VALUE = 'RECEIVE_PRODUCT_SEARCH_VALUE';
export const RECEIVE_PRODUCT_LIST = 'RECEIVE_PRODUCT_LIST';
export const RECEIVE_PRODUCT_ID_LIST = 'RECEIVE_PRODUCT_ID_LIST';
export const RECEIVE_PRODUCT = 'RECEIVE_PRODUCT';
export const RECEIVE_PRODUCT_NAME = 'RECEIVE_PRODUCT_NAME';
export const RECEIVE_PRODUCT_PRICE = 'RECEIVE_PRODUCT_PRICE';
export const RECEIVE_PRODUCT_UNIT = 'RECEIVE_PRODUCT_UNIT';
export const RECEIVE_PRODUCT_AMOUNT = 'RECEIVE_PRODUCT_AMOUNT';
export const RECEIVE_PRODUCT_DESCRIPTION = 'RECEIVE_PRODUCT_DESCRIPTION';
export const RECEIVE_PRODUCT_ERROR_MESSAGES = 'RECEIVE_PRODUCT_ERROR_MESSAGES';
export const RECEIVE_PRODUCT_ERROR_MESSAGES_PRODUCT_TYPE =
  'RECEIVE_PRODUCT_ERROR_MESSAGES_PRODUCT_TYPE';
export const RECEIVE_PRODUCT_ERROR_MESSAGES_MENU_TYPE = 'RECEIVE_PRODUCT_ERROR_MESSAGES_MENU_TYPE';
export const RECEIVE_PRODUCT_ERROR_MESSAGES_NAME = 'RECEIVE_PRODUCT_ERROR_MESSAGES_NAME';
export const RECEIVE_PRODUCT_ERROR_MESSAGES_PRICE = 'RECEIVE_PRODUCT_ERROR_MESSAGES_PRICE';
export const RECEIVE_PRODUCT_ERROR_MESSAGES_UNIT = 'RECEIVE_PRODUCT_ERROR_MESSAGES_UNIT';
export const RECEIVE_PRODUCT_ERROR_MESSAGES_AMOUNT = 'RECEIVE_PRODUCT_ERROR_MESSAGES_AMOUNT';
export const RECEIVE_PRODUCT_EDIT_OPEN_FLAG = 'RECEIVE_PRODUCT_EDIT_OPEN_FLAG';

/** user */
export const RECEIVE_LOGIN_USER_DATA = 'RECEIVE_LOGIN_USER_DATA';
export const RECEIVE_USER_SEARCH_VALUE = 'RECEIVE_USER_SEARCH_VALUE';
export const RECEIVE_USER_LIST = 'RECEIVE_USER_LIST';
export const RECEIVE_USER_ID_LIST = 'RECEIVE_USER_ID_LIST';
export const RECEIVE_USER = 'RECEIVE_USER';
export const RECEIVE_USER_USERNAME = 'RECEIVE_USER_USERNAME';
export const RECEIVE_USER_PASSWORD = 'RECEIVE_USER_PASSWORD';
export const RECEIVE_USER_ERROR_MESSAGES = 'RECEIVE_USER_ERROR_MESSAGES';
export const RECEIVE_USER_ERROR_MESSAGE_USER_TYPE = 'RECEIVE_USER_ERROR_MESSAGES_USER_TYPE';
export const RECEIVE_USER_ERROR_MESSAGE_USERNAME = 'RECEIVE_USER_ERROR_MESSAGES_USERNAME';
export const RECEIVE_USER_ERROR_MESSAGE_PASSWORD = 'RECEIVE_USER_ERROR_MESSAGES_PASSWORD';
export const RECEIVE_USER_EDIT_OPEN_FLAG = 'RECEIVE_PRODUCT_EDIT_OPEN_FLAG';

/** images */
export const RECEIVE_IMAGE_FILES = 'RECEIVE_IMAGE_FILES';
export const RECEIVE_IMAGE_FILES_NAME = 'RECEIVE_IMAGE_FILES_NAME';
export const RECEIVE_IMAGE_ERROR_MESSAGE = 'RECEIVE_IMAGE_ERROR_MESSAGE';

/** order detail */
export const RECEIVE_ORDER = 'RECEIVE_ORDER';
export const RECEIVE_ORDER_DETAIL_LIST = 'RECEIVE_ORDER_DETAIL_LIST';
export const RECEIVE_ORDER_DETAIL = 'RECEIVE_ORDER_DETAIL';
export const RECEIVE_ORDER_FINAL_PRICE = 'RECEIVE_ORDER_FINAL_PRICE';
