/* product type */
export const GET_PRODUCT_TYPE_LIST: string = "GET_PRODUCT_TYPE_LIST";
export const GET_PRODUCT_TYPE: string = "GET_PRODUCT_TYPE";
export const GET_PRODUCT_TYPE_ID: string = "GET_PRODUCT_TYPE_ID";
export const RECEIVE_PRODUCT_TYPE: string = "RECEIVE_PRODUCT_TYPE";

/* menu type */
export const GET_MENU_TYPE_LIST: string = "GET_MENU_TYPE_LIST";
export const GET_MENU_TYPE: string = "GET_MENU_TYPE";
export const GET_MENU_TYPE_ID: string = "GET_MENU_TYPE_ID";
export const RECEIVE_MENU_TYPE: string = "RECEIVE_MENU_TYPE";

/* product */
export const GET_PRODUCT_LIST: string = "GET_PRODUCT_LIST";
export const GET_PRODUCT: string = "GET_PRODUCT";
export const RECEIVE_PRODUCT_SEARCH_VALUE: string = "RECEIVE_PRODUCT_SEARCH_VALUE";
export const RECEIVE_PRODUCT_TABLE_HEAD_CELLS: string = "RECEIVE_PRODUCT_TABLE_HEAD_CELLS";
export const RECEIVE_PRODUCT: string = "RECEIVE_PRODUCT";
export const RECEIVE_PRODUCT_ID_LIST: string = "RECEIVE_PRODUCT_ID_LIST";
export const RECEIVE_PRODUCT_NAME: string = "RECEIVE_PRODUCT_NAME";
export const RECEIVE_PRODUCT_PRICE: string = "RECEIVE_PRODUCT_PRICE";
export const RECEIVE_PRODUCT_UNIT: string = "RECEIVE_PRODUCT_UNIT";
export const RECEIVE_PRODUCT_AMOUNT: string = "RECEIVE_PRODUCT_AMOUNT";
export const RECEIVE_PRODUCT_DESCRIPTION: string = "RECEIVE_PRODUCT_DESCRIPTION";
export const RECEIVE_PRODUCT_ERROR_MESSAGES: string = "RECEIVE_PRODUCT_ERROR_MESSAGES";
export const RECEIVE_PRODUCT_EDIT_OPEN_FLAG: string = "RECEIVE_PRODUCT_EDIT_OPEN_FLAG";

/* user */
export const GET_USER_LIST: string = "GET_USER_LIST";
export const GET_USER: string = "GET_USER";
export const RECEIVE_LOGIN_USER_DATA: string = "RECEIVE_LOGIN_USER_DATA";
export const RECEIVE_USER_TABLE_HEAD_CELLS: string = "RECEIVE_USER_TABLE_HEAD_CELLS";
export const RECEIVE_USER: string = "RECEIVE_USER";
export const RECEIVE_USER_ID_LIST: string = "RECEIVE_USER_ID_LIST";
export const RECEIVE_USER_EDIT_OPEN_FLAG: string = "RECEIVE_PRODUCT_EDIT_OPEN_FLAG";

/* images */
export const RECEIVE_IMAGE_FILES: string = "RECEIVE_IMAGE_FILES";
export const RECEIVE_IMAGE_ERROR_MESSAGE: string = "RECEIVE_IMAGE_ERROR_MESSAGE";